### ISSUE TITLE
Move recipes folder inside .pybombs

### ISSUE THREAD

**Issue by sdh11** [gnuradio/pybombs2#35]
This would make the prefix folder much cleaner; it would only have the installed binaries.

**Comment by sdh11** [comment]
I also have a tested branch with this I can push. Small change.

**Comment by mbr0wn** [comment]
recipes, OK, but src, I'm not a fan of. Particularly when you set $prefix to /usr/local, you'd have /usr/local/src as the default -- which is also a Linux default.

Browsing into the src dir is also quite common. The cross compile stuff would break, btw, because it uses relative paths to find toolchain cmake files.

What's worse, it hides the src dir from casual peeks, but it can get pretty big. 'cleaner' is such a subjective term, too :)

**Comment by mbr0wn** [comment]
Alternative src dirs can be set when running `pybombs init`.
