### ISSUE TITLE
Deploy command

### ISSUE THREAD

**Issue by sdh11** [gnuradio/pybombs2#5]
Creates a compressed archive with all the built packages

**Comment by mbr0wn** [comment]
$ pybombs deploy [flags] [output_file]

Does not include source directory.

Flags:
* `-j`, `--bzip2`: Use bzip2
* `-z`, `--gzip`: Use gzip (default)
* `-J`, `--xz`: Use xz

Output file name is either:
* `output_file` if that is give on the command line or
* <prefix_alias>.tar.gz if a prefix alias is known, or 
* `pybombs_prefix.tar.gz` otherwise.

**Comment by mbr0wn** [comment]
We may have some specifics for cross-compiled stuff.

**Comment by mbr0wn** [comment]
- Do we include the src/ directory? (maybe optional)
- Do we include the .pybombs directory? (maybe optional)

**Comment by mbr0wn** [comment]
2288d53e0caedd81051532375dd331f587080a54
